ND2_hw/TicketsReselling/Models/AddTicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicketsReselling.Models
{
    public class AddTicketViewModel
    {
        [Required]
        public int Price { get; set; }
        public string Notes { get; set; }
    }
}

ND2_hw/TicketsReselling/Models/AddTrackingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicketsReselling.Models
{
    public class AddTrackingViewModel
    {
        public int TicketId { get; set; }
        [Required]
        public string TrackingNumber { get; set; }
    }
}

ND2_hw/TicketsReselling/Models/TicketsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketsReselling.DAL.Enums;

namespace TicketsReselling.Models
{
    public class TicketsViewModel
    {
        public TicketView[] Tickets { get; set; }
    }

    public class TicketView
    {
        public int TicketId{ get; set; }
        public TicketStatuses TicketStatus{ get; set; }
        public string BuyerName  { get; set; }
        public string BuyerId  { get; set; }
        public decimal TicketPrice { get; set; }
        public string EventName { get; set; }
        public int EventId { get; set; }
        public int? OrderId { get; set; }
        public string OrderTrackingNumber { get; set; }
        public DateTime EventDate { get; set; }
    }
}

ND2_hw/TicketsReselling/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TicketsReselling.DAL.Enums;
using TicketsReselling.Business.Models;
using TicketsReselling.Core;
using TicketsReselling.DAL.Models;
using TicketsReselling.Models;
using TicketsReselling.Core.Interfaces;

namespace TicketsReselling.Controllers
{
    public class EventsController : Controller
    {
        private readonly ITicketsService ticketsService;
        private readonly IEventsService eventsService;
        private readonly IVenuesService venuesService;
        private readonly ICitiesService citiesService;
        private readonly UserManager<User> userManager;
        private readonly IStringLocalizer<EventsController> stringLocalizer;

        public EventsController(
            ITicketsService ticketsService,
            IEventsService eventsService,
            IVenuesService venuesService,
            ICitiesService citiesService,
            UserManager<User> userManager,
            IStringLocalizer<EventsController> stringLocalizer)
        {
            this.ticketsService = ticketsService;
            this.venuesService = venuesService;
            this.citiesService = citiesService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.stringLocalizer = stringLocalizer;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = stringLocalizer["eventpagetitle"];

            var model = new EventsViewModel
            {
                Categories = await eventsService.GetCategories(),
                Cities = await citiesService.GetCityesByStatus(CityStatuses.Avaliable)
            };

            return View(model);
        }

        public async Task<IActionResult> EventWithTickets(int eventId)
        {
            var currentEvent = await eventsService.GetEventById(eventId);
            var eventTickets = ticketsService.GetTicketsByEventIdAndStatus(eventId, TicketStatuses.Selling);
            currentEvent.Venue = await venuesService.GetVenueById(currentEvent.VenueId);
            currentEvent.Venue.City = await citiesService.GetCityById(currentEvent.Venue.CityId);
            var ticketsList = new List<EventTickets>();

            foreach (var ticket in eventTickets)
            {
                var seller = await userManager.FindByIdAsync(ticket.SellerId);

                ticketsList.Add(
                    new EventTickets
                    {
                        TicketId = ticket.Id,
                        SellerName = seller.UserName,
                        Price = ticket.Price,
                        SellerNotes = ticket.SellerNotes
                    }
                );
            };

            var model = new EventWithTicketsViewModel
            {
                Event = currentEvent,
                Tickets = ticketsList
            };

            return View(model);
        }

        [Authorize(Roles = UserRoles.Administrator)]
        public async Task<IActionResult> AddEvent()
        {
            ViewBag.categories = await eventsService.GetCategories();
            ViewBag.venues = await venuesService.GetVenuesByStatuses(VenueStatuses.Avaliable);
            return View();
        }

        [Authorize(Roles = UserRoles.Administrator)]
        [HttpPost]
        public async Task<IActionResult> AddEvent(AddEventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                var bannerName = FileUploader.UploadFile(newEvent.Banner).Result;

                await eventsService.AddEvent(new Event
                {
                    Description = newEvent.Description,
                    Name = newEvent.Name,
                    Banner = bannerName,
                    Category = await eventsService.GetCategoryById(newEvent.CategoryId),
                    Date = newEvent.Date,
                    Venue = await venuesService.GetVenueById(newEvent.VenueId)
                });

                return View("InstructionEventAdded");
            }

            return View("Index");
        }

        [Authorize(Roles = UserRoles.Administrator)]
        public async Task<IActionResult> RemoveEvent(int eventId)
        {
            var eventItem = await eventsService.GetEventById(eventId);
            await eventsService.ChangeEventStatus(eventItem, EventStatuses.Removed);

            return View("InstructionEventRemoved");
        }
    }
}

ND2_hw/TicketsReselling/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TicketsReselling.DAL.Enums;
using TicketsReselling.Business.Models;
using TicketsReselling.Core;
using TicketsReselling.DAL.Models;
using TicketsReselling.Models;
using TicketsReselling.Core.Interfaces;

namespace TicketsReselling.Controllers
{
    [Authorize(Roles = UserRoles.User)]
    public class OrdersController : Controller
    {
        private readonly ITicketsService ticketsService;
        private readonly IEventsService eventsService;
        private readonly IOrdersService ordersService;
        private readonly UserManager<User> userManager;
        private readonly IStringLocalizer<EventsController> stringLocalizer;

        public OrdersController(
            ITicketsService ticketsService,
            IEventsService eventsService,
            IOrdersService ordersService,
            UserManager<User> userManager,
            IStringLocalizer<EventsController> stringLocalizer)
        {
            this.ticketsService = ticketsService;
            this.ordersService = ordersService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.stringLocalizer = stringLocalizer;
        }

        public async Task<IActionResult> Index()
        {
            var currentUserId = userManager.GetUserId(User);
            var userOrders = await ordersService.GetOrdersByUserId(currentUserId);
            var myOrders = new List<OrderView> { };

            foreach (var order in userOrders)
            {
                var orderTicket = await ticketsService.GetTicketById(order.TicketId);
                var ticketEvent = await eventsService.GetEventById(orderTicket.EventId);

                myOrders.Add(
                    new OrderView
                    {
                        OrderId = order.Id,
                        TicketPrice = orderTicket.Price,
                        OrderStatus = order.Status,
                        SellerName = (await userManager.FindByIdAsync(orderTicket.SellerId))?.UserName,
                        SellerId = orderTicket.SellerId,
                        EventId = orderTicket.EventId,
                        EventName = ticketEvent.Name,
                        EventDate = ticketEvent.Date,
                    }
                );
            };

            var model = new OrderViewModel
            {
                Orders = myOrders.ToArray()
            };

            return View(model);
        }

        public async Task<IActionResult> AddOrder(int ticketId)
        {
            var ticket = await ticketsService.GetTicketById(ticketId);
            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.WaitingForConfirmation);

            await ordersService.AddOrder(new Order
            {
                TicketId = ticket.Id,
                Status = (int)OrderStatuses.WaitingForConfirmation,
                UserId = userManager.GetUserId (User)
            });

            return View("InstructionOrderAdded");
        }

        public async Task<IActionResult> CancelOrder(int orderId)
        {
            var order = await ordersService.GetOrderById(orderId);
            var ticket = await ticketsService.GetTicketById(order.TicketId);

            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.Selling);
            await ordersService.ChangeOrderStatus(order, OrderStatuses.Cancelled);

            return View("InstructionOrderCanceled");
        }

        public async Task<IActionResult> TrackingInfo(int orderId)
        {
            ViewBag.trackingNumber = (await ordersService.GetOrderById(orderId))?.TrackingNumber;

            return View("TrackingNumberInfo");
        }

        public async Task<IActionResult> ConfirmOrderReceiving(int orderId)
        {
            var order = await ordersService.GetOrderById(orderId);
            var ticket = await ticketsService.GetTicketById(order.TicketId);

            await ordersService.ChangeOrderStatus(order, OrderStatuses.Completed);
            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.Sold);

            return View("InstructionOrderReceivingConfirmed");
        }

        public async Task<IActionResult> RemoveOrder(int orderId)
        {
            var order = await ordersService.GetOrderById(orderId);

            await ordersService.ChangeOrderStatus(order, OrderStatuses.Removed);

            return View("InstructionOrderRemoved");
        }
    }
}

ND2_hw/TicketsReselling/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TicketsReselling.DAL.Enums;
using TicketsReselling.Business.Models;
using TicketsReselling.Core;
using TicketsReselling.DAL.Models;
using TicketsReselling.Models;
using TicketsReselling.Core.Interfaces;

namespace TicketsReselling.Controllers
{
    [Authorize(Roles = UserRoles.User)]
    public class TicketsController : Controller
    {
        private readonly ITicketsService ticketsService;
        private readonly IEventsService eventsService;
        private readonly IOrdersService ordersService;
        private readonly UserManager<User> userManager;
        private readonly IStringLocalizer<EventsController> stringLocalizer;

        public TicketsController(
            ITicketsService ticketsService,
            IEventsService eventsService,
            IOrdersService ordersService,
            UserManager<User> userManager,
            IStringLocalizer<EventsController> stringLocalizer)
        {
            this.ticketsService = ticketsService;
            this.ordersService = ordersService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.stringLocalizer = stringLocalizer;
        }

        public async Task<IActionResult> Index()
        {
            var currentUserId = userManager.GetUserId(User);
            var userTickets = await ticketsService.GetTicketsByUserId(currentUserId);
            var myTickets = new List<TicketView> { };

            foreach (var ticket in userTickets)
            {
                var ticketEvent = await eventsService.GetEventById(ticket.EventId);
                var ticketOrder = await ordersService.GetOrderByTicketIdAndStatuses(ticket.Id, OrderStatuses.WaitingForConfirmation, OrderStatuses.Confirmed, OrderStatuses.Completed);
                var orderUser = await userManager.FindByIdAsync(ticketOrder?.UserId);

                myTickets.Add(
                    new TicketView
                    {
                        TicketId = ticket.Id,
                        TicketPrice = ticket.Price,
                        TicketStatus = ticket.Status,
                        BuyerName = orderUser?.UserName,
                        BuyerId = orderUser?.Id,
                        OrderId = ticketOrder?.Id,
                        EventName = ticketEvent.Name,
                        EventId = ticket.EventId,
                        EventDate = ticketEvent.Date,
                        OrderTrackingNumber = ticketOrder?.TrackingNumber
                    }
                );
            };

            var model = new TicketsViewModel
            {
                Tickets = myTickets.ToArray()
            };

            return View(model);
        }

        public async Task<IActionResult> AddTicket(int eventId)
        {
            ViewBag.EventId = eventId;
            ViewBag.EventName = (await eventsService.GetEventById(eventId))?.Name;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTicket(AddTicketViewModel ticketModel, int eventId)
        {
            var ticket = new Ticket
            {
                EventId = eventId,
                SellerId = userManager.GetUserId(User),
                Price = ticketModel.Price,
                SellerNotes = ticketModel.Notes,
                Status = TicketStatuses.Selling
            };

            await ticketsService.AddTicket(ticket);

            return View("InstructionTicketAdded");
        }

        public async Task<IActionResult> RemoveTicket(int ticketId)
        {
            var ticket = await ticketsService.GetTicketById(ticketId);
            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.Removed);

            return View("InstructionTicketDeleted");
        }

        public async Task<IActionResult> ConfirmOrder(int ticketId)
        {
            var ticket = await ticketsService.GetTicketById(ticketId);
            var order = await ordersService.GetOrderByTicketIdAndStatuses(ticket.Id, OrderStatuses.WaitingForConfirmation);

            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.WaitingForReceivingConfirmation);
            await ordersService.ChangeOrderStatus(order, OrderStatuses.Confirmed);

            return View("InstructionOrderConfirmed");
        }

        public async Task<IActionResult> RejectOrder(int ticketId)
        {
            var ticket = await ticketsService.GetTicketById(ticketId);
            var order = await ordersService.GetOrderByTicketIdAndStatuses(ticket.Id, OrderStatuses.WaitingForConfirmation);

            await ticketsService.ChangeTicketStatus(ticket, TicketStatuses.Selling);
            await ordersService.ChangeOrderStatus(order, OrderStatuses.Rejected);

            return View("InstructionOrderRejected");
        }

        public IActionResult AddTracking(int ticketId)
        {
            ViewBag.ticketId = ticketId;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTracking(AddTrackingViewModel tracking)
        {
            var ticket = await ticketsService.GetTicketById(tracking.TicketId);
            var order = await ordersService.GetOrderByTicketIdAndStatuses(ticket.Id, OrderStatuses.Confirmed);

            await ordersService.ChangeOrderTracking(order, tracking.TrackingNumber);

            return View("InstructionTrackingAdded");
        }
    }
}

ND2_hw/TicketsReselling/Views/Tickets/AddTicket.cshtml
@model TicketsReselling.Models.AddTicketViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "AddTicket";
}

<h3>@Localizer["AddingTicket"]</h3>
<h3>@ViewBag.EventName</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddTicket">
            <input type="hidden" value="@ViewBag.EventId" name="eventId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>@Localizer["Price"]</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["Notes"]</label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Add"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ND2_hw/TicketsReselling/Views/Tickets/AddTracking.cshtml
@model TicketsReselling.Models.AddTrackingViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "AddTracking";
}

<h3>@Localizer["AddingTrecking"]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddTracking">
            <input type="hidden" value="@ViewBag.TicketId" name="TicketId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>@Localizer["EnterTracking"]</label>
                <input asp-for="TrackingNumber" class="form-control" />
                <span asp-validation-for="TrackingNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Submit"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ND2_hw/TicketsReselling/Views/Tickets/Index.cshtml
@model TicketsViewModel
@using TicketsReselling.DAL.Enums;
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "MyTickets";
}

<h2>@Localizer["MyTickets"]</h2>
<div class="container-fluid pt-2">
    <div class="row pt-2 mb-2" style="border-bottom-style:groove">
        <div class="col-md-3 text-center ">
            @Localizer["Event"]
        </div>
        <div class="col-md-2 text-center">
            @Localizer["EventDate"]
        </div>
        <div class="col-md-2 text-center">
            @Localizer["PriceUSD"]
        </div>
        <div class="col-md-3 text-center">
            @Localizer["Buyer"]
        </div>
        <div class="col-md-2 text-center">
            @Localizer["Actions"]
        </div>
    </div>
    <div class="col-md-12 pt-2 text-center" style="text-decoration: underline">
        @Localizer["WaitingForConfirmation"]
    </div>

    @if (Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.WaitingForConfirmation).Count() == 0)
    {
        <div class="col-md-12 text-center text-info">
            @Localizer["NoTickets"]
        </div>
    }

    @foreach (var ticket in Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.WaitingForConfirmation))
    {
        <div class="row">
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.EventName, "EventWithTickets", "Events", new { eventId = ticket.EventId })
            </div>
            <div class="col-md-2 text-center">
                @ticket.EventDate.ToShortDateString()
            </div>
            <div class="col-md-2 text-center">
                @ticket.TicketPrice
            </div>
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.BuyerName, "PublicInfo", "Users", new { userId = ticket.BuyerId })
            </div>
            <div class="col-md-1">
                @Html.ActionLink(Localizer["Confirm"].Value.ToString(), "ConfirmOrder", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
            </div>
            <div class="col-md-1">
                @Html.ActionLink(Localizer["Reject"].Value.ToString(), "RejectOrder", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
            </div>
        </div>
    }
    <div class="col-md-12 pt-4 text-center" style="text-decoration:underline">
        @Localizer["Selling"]
    </div>

    @if (Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.Selling).Count() == 0)
    {
        <div class="col-md-12 text-center text-info">
            @Localizer["NoTickets"]
        </div>
    }

    @foreach (var ticket in Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.Selling))
    {
        <div class="row">
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.EventName, "EventWithTickets", "Events", new { eventId = ticket.EventId })
            </div>
            <div class="col-md-2 text-center">
                @ticket.EventDate.ToShortDateString()
            </div>
            <div class="col-md-2 text-center">
                @ticket.TicketPrice
            </div>
            <div class="col-md-3 text-center">
                @Localizer["NoBuyerYet"]
            </div>
            <div class="col-md-2">
                @Html.ActionLink(Localizer["Delete"].Value.ToString(), "RemoveTicket", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
            </div>
        </div>
    }

    <div class="col-md-12 pt-4 text-center" style="text-decoration:underline">
        @Localizer["WaitingForReceivingConfirmation"]
    </div>

    @if (Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.WaitingForReceivingConfirmation).Count() == 0)
    {
        <div class="col-md-12 text-center text-info">
            @Localizer["NoTickets"]
        </div>
    }

    @foreach (var ticket in Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.WaitingForReceivingConfirmation))
    {
        <div class="row">
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.EventName, "EventWithTickets", "Events", new { eventId = ticket.EventId })
            </div>
            <div class="col-md-2 text-center">
                @ticket.EventDate.ToShortDateString()
            </div>
            <div class="col-md-2 text-center">
                @ticket.TicketPrice
            </div>
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.BuyerName, "PublicInfo", "Users", new { userId = ticket.BuyerId })
            </div>

            @if (string.IsNullOrEmpty(ticket.OrderTrackingNumber))
            {
                <div class="col-md-2">
                    @Html.ActionLink(Localizer["AddTrack"].Value.ToString(), "AddTracking", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
                </div>

            }
            else
            {
                <div class="col-md-1">
                    @Html.ActionLink(Localizer["Info"].Value.ToString(), "TrackingInfo", "Orders", new { orderId =ticket.OrderId }, new { @class = "btn btn-primary pt-1 mb-1" })
                </div>
                <div class="col-md-1">
                    @Html.ActionLink(Localizer["ChangeTrack"].Value.ToString(), "AddTracking", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
                </div>
            }
        </div>
    }

    <div class="col-md-12 pt-4 text-center" style="text-decoration:underline">
        @Localizer["Sold"]
    </div>

    @if (Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.Sold).Count() == 0)
    {
        <div class="col-md-12 text-center text-info">
            @Localizer["NoTickets"]
        </div>
    }

    @foreach (var ticket in Model.Tickets.Where(t => t.TicketStatus == TicketStatuses.Sold))
    {
        <div class="row">
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.EventName, "EventWithTickets", "Events", new { eventId = ticket.EventId })
            </div>
            <div class="col-md-2 text-center">
                @ticket.EventDate.ToShortDateString()
            </div>
            <div class="col-md-2 text-center">
                @ticket.TicketPrice
            </div>
            <div class="col-md-3 text-center">
                @Html.ActionLink(ticket.BuyerName, "PublicInfo", "Users", new { userId = ticket.BuyerId })
            </div>
            <div class="col-md-2">
                @Html.ActionLink(Localizer["Delete"].Value.ToString(), "RemoveTicket", "Tickets", new { ticketId = ticket.TicketId }, new { @class = "btn btn-primary pt-1 mb-1" })
            </div>
        </div>
    }
</div>

ND2_hw/TicketsReselling/Views/Tickets/InstructionOrderConfirmed.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "InstructionOrderConfirmed";
}

<h4>@Localizer["InstructionOrderConfirmed"]</h4>

ND2_hw/TicketsReselling/Views/Tickets/InstructionOrderRejected.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "InstructionOrderRejected";
}

<h4>@Localizer["InstructionOrderRejected"]</h4>

ND2_hw/TicketsReselling/Views/Tickets/InstructionTicketAdded.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "InstructionTicketAdded";
}

<h4>@Localizer["InstructionTicketAdded"]</h4>

ND2_hw/TicketsReselling/Views/Tickets/InstructionTicketDeleted.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "InstructionTicketDeleted";
}

<h4>@Localizer["InstructionTicketDeleted"]</h4>

ND2_hw/TicketsReselling/Views/Tickets/InstructionTrackingAdded.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

@{
    ViewData["Title"] = "InstructionTrackingAdded";
}

<h4>@Localizer["InstructionTrackingAdded"]</h4>