ND2_hw/TicketsReselling/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using TicketsReselling.DAL.Enums;
using TicketsReselling.Business.Models;
using TicketsReselling.Core;
using TicketsReselling.DAL.Models;
using TicketsReselling.Models;
using TicketsReselling.Core.Interfaces;

namespace TicketsReselling.Controllers
{
    public class EventsController : Controller
    {
        private readonly ITicketsService ticketsService;
        private readonly IEventsService eventsService;
        private readonly IVenuesService venuesService;
        private readonly ICitiesService citiesService;
        private readonly UserManager<User> userManager;
        private readonly IStringLocalizer<EventsController> stringLocalizer;

        public EventsController(
            ITicketsService ticketsService,
            IEventsService eventsService,
            IVenuesService venuesService,
            ICitiesService citiesService,
            UserManager<User> userManager,
            IStringLocalizer<EventsController> stringLocalizer)
        {
            this.ticketsService = ticketsService;
            this.venuesService = venuesService;
            this.citiesService = citiesService;
            this.eventsService = eventsService;
            this.userManager = userManager;
            this.stringLocalizer = stringLocalizer;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = stringLocalizer["eventpagetitle"];

            var model = new EventsViewModel
            {
                Categories = await eventsService.GetCategories(),
                Cities = await citiesService.GetCityesByStatus(CityStatuses.Avaliable)
            };

            return View(model);
        }

        public async Task<IActionResult> EventWithTickets(int eventId)
        {
            var currentEvent = await eventsService.GetEventById(eventId);
            var eventTickets = ticketsService.GetTicketsByEventIdAndStatus(eventId, TicketStatuses.Selling);
            currentEvent.Venue = await venuesService.GetVenueById(currentEvent.VenueId);
            currentEvent.Venue.City = await citiesService.GetCityById(currentEvent.Venue.CityId);
            var ticketsList = new List<EventTickets>();

            foreach (var ticket in eventTickets)
            {
                var seller = await userManager.FindByIdAsync(ticket.SellerId);

                ticketsList.Add(
                    new EventTickets
                    {
                        TicketId = ticket.Id,
                        SellerName = seller.UserName,
                        Price = ticket.Price,
                        SellerNotes = ticket.SellerNotes
                    }
                );
            };

            var model = new EventWithTicketsViewModel
            {
                Event = currentEvent,
                Tickets = ticketsList
            };

            return View(model);
        }

        [Authorize(Roles = UserRoles.Administrator)]
        public async Task<IActionResult> AddEvent()
        {
            ViewBag.categories = await eventsService.GetCategories();
            ViewBag.venues = await venuesService.GetVenuesByStatuses(VenueStatuses.Avaliable);
            return View();
        }

        [Authorize(Roles = UserRoles.Administrator)]
        [HttpPost]
        public async Task<IActionResult> AddEvent(AddEventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                var bannerName = FileUploader.UploadFile(newEvent.Banner).Result;

                await eventsService.AddEvent(new Event
                {
                    Description = newEvent.Description,
                    Name = newEvent.Name,
                    Banner = bannerName,
                    Category = await eventsService.GetCategoryById(newEvent.CategoryId),
                    Date = newEvent.Date,
                    Venue = await venuesService.GetVenueById(newEvent.VenueId)
                });

                return View("InstructionEventAdded");
            }

            return View("Index");
        }

        [Authorize(Roles = UserRoles.Administrator)]
        public async Task<IActionResult> RemoveEvent(int eventId)
        {
            var eventItem = await eventsService.GetEventById(eventId);
            await eventsService.ChangeEventStatus(eventItem, EventStatuses.Removed);

            return View("InstructionEventRemoved");
        }
    }
}

ND2_hw/TicketsReselling/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace TicketsReselling.Controllers
{
    public class LanguageController : Controller
    {
        public IActionResult SetLanguage(string locale, string returnUrl, string queryString)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(locale)));

            if (!String.IsNullOrEmpty(returnUrl))
            {
                if (!String.IsNullOrEmpty(queryString))
                {
                    returnUrl += queryString;
                }

                return LocalRedirect(returnUrl);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ND2_hw/TicketsReselling/Views/Shared/_LanguagePartial.cshtml
@using TicketsReselling.Business.Models
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<ul class="navbar-nav flex-grow-2">
    @if (System.Globalization.CultureInfo.CurrentCulture.Name == Locales.SupportedLocales[0])
    {
        <li class="nav-item">
            @Html.ActionLink("RU", "SetLanguage", "Language", new { locale = Locales.SupportedLocales[1], returnUrl = Context.Request.Path, queryString = Context.Request.QueryString.Value })
        </li>
    }
    else if (System.Globalization.CultureInfo.CurrentCulture.Name == Locales.SupportedLocales[1])
    {
        <li class="nav-item">
            @Html.ActionLink("EN", "SetLanguage", "Language", new { locale = Locales.SupportedLocales[0], returnUrl = Context.Request.Path, queryString = Context.Request.QueryString.Value })
        </li>
    }
</ul>

ND2_hw/TicketsReselling/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketsReselling</title>
    <script src="~/dist/site.entry.js" type="module" defer></script>
    <link rel="stylesheet" href="~/dist/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LanguagePartial" />
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">@Localizer["Events"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TicketsReselling - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>